const { join } = require('path');

/** @type {import('tailwindcss').Config} */
module.exports = {
  content: [
    join(__dirname, 'apps/web/src/**/*.{html,ts}'),
  ],
  theme: {
    extend: {},
  },
  plugins: [require('daisyui')],
  daisyui: {
    themes: [
      {
        light: {
          ...require('daisyui/src/theming/themes')['light'],
          primary: '#4f46e5',
          'primary-content': '#ffffff',
          secondary: '#0ea5e9',
          accent: '#10b981',
          'base-100': '#ffffff',
          'base-200': '#f6f8fb',
          'base-300': '#e3e8f0',
        },
        // ---- Refined Indigo (modern default light) -------------------------
        indigo: {
          ...require('daisyui/src/theming/themes')['light'],
          primary: '#4f46e5',
          'primary-content': '#ffffff',
          secondary: '#0ea5e9',
          'secondary-content': '#ffffff',
          accent: '#10b981',
          'accent-content': '#ffffff',
          neutral: '#1e293b',
          'neutral-content': '#f8fafc',
          'base-100': '#ffffff',
          'base-200': '#f4f6fb',
          'base-300': '#e2e8f3',
          'base-content': '#1e293b',
          info: '#0ea5e9',
          success: '#16a34a',
          warning: '#f59e0b',
          error: '#ef4444',
        },
        // ---- Slate + Violet (premium / editorial) --------------------------
        violet: {
          ...require('daisyui/src/theming/themes')['light'],
          primary: '#6d28d9',
          'primary-content': '#ffffff',
          secondary: '#7c3aed',
          'secondary-content': '#ffffff',
          accent: '#f59e0b',
          'accent-content': '#1c1917',
          neutral: '#1c1917',
          'neutral-content': '#fafaf9',
          'base-100': '#ffffff',
          'base-200': '#f5f5f7',
          'base-300': '#e5e5ea',
          'base-content': '#1c1917',
          info: '#6366f1',
          success: '#16a34a',
          warning: '#f59e0b',
          error: '#e11d48',
        },
        // ---- Teal Fintech (calm, data-focused) -----------------------------
        teal: {
          ...require('daisyui/src/theming/themes')['light'],
          primary: '#0f766e',
          'primary-content': '#ffffff',
          secondary: '#0891b2',
          'secondary-content': '#ffffff',
          accent: '#f59e0b',
          'accent-content': '#0f172a',
          neutral: '#0f172a',
          'neutral-content': '#f1f5f9',
          'base-100': '#ffffff',
          'base-200': '#f1f5f5',
          'base-300': '#dce5e5',
          'base-content': '#0f172a',
          info: '#0891b2',
          success: '#15803d',
          warning: '#d97706',
          error: '#dc2626',
        },
        // ---- Mono + Accent (minimal, high-contrast) ------------------------
        mono: {
          ...require('daisyui/src/theming/themes')['light'],
          primary: '#18181b',
          'primary-content': '#ffffff',
          secondary: '#4f46e5',
          'secondary-content': '#ffffff',
          accent: '#4f46e5',
          'accent-content': '#ffffff',
          neutral: '#18181b',
          'neutral-content': '#fafafa',
          'base-100': '#ffffff',
          'base-200': '#fafafa',
          'base-300': '#e4e4e7',
          'base-content': '#18181b',
          info: '#4f46e5',
          success: '#16a34a',
          warning: '#f59e0b',
          error: '#ef4444',
        },
        // ---- Coral Sunset (warm & colorful) --------------------------------
        sunset: {
          ...require('daisyui/src/theming/themes')['light'],
          primary: '#f97316',
          'primary-content': '#ffffff',
          secondary: '#ec4899',
          'secondary-content': '#ffffff',
          accent: '#8b5cf6',
          'accent-content': '#ffffff',
          neutral: '#431407',
          'neutral-content': '#fff7ed',
          'base-100': '#ffffff',
          'base-200': '#fff7ed',
          'base-300': '#fde4cf',
          'base-content': '#431407',
          info: '#0ea5e9',
          success: '#16a34a',
          warning: '#f59e0b',
          error: '#e11d48',
        },
        // ---- Candy Pop (playful & colorful) --------------------------------
        candy: {
          ...require('daisyui/src/theming/themes')['light'],
          primary: '#d946ef',
          'primary-content': '#ffffff',
          secondary: '#8b5cf6',
          'secondary-content': '#ffffff',
          accent: '#06b6d4',
          'accent-content': '#ffffff',
          neutral: '#4a044e',
          'neutral-content': '#fdf4ff',
          'base-100': '#ffffff',
          'base-200': '#fdf4ff',
          'base-300': '#f5d0fe',
          'base-content': '#4a044e',
          info: '#06b6d4',
          success: '#10b981',
          warning: '#f59e0b',
          error: '#f43f5e',
        },
        dark: {
          ...require('daisyui/src/theming/themes')['dark'],
          primary: '#6366f1',
          'primary-content': '#ffffff',
          secondary: '#0ea5e9',
          accent: '#10b981',
          'base-100': '#131a2b',
          'base-200': '#0e1422',
          'base-300': '#232c44',
        },
      },
    ],
    darkTheme: 'dark',
    base: true,
    styled: true,
    utils: true,
    logs: false,
  },
};
